### ISSUE TITLE
Doesn't show menuconfig when config doesn't exist

### ISSUE THREAD

**Issue by thomasfjen** [fbeauKmi/update_klipper_and_mcus#6]
Hey there! Thank you for the great tool!
It really makes updating the firmwares of the various mcu's a breeze.

One thing which i found out while doing the first run is that the following case did not work: 
> Do make menuconfig before firmware build, without this option the Menuconfig is displayed only while config file for the mcu doesn't exists.
There were no configs saved and it just started compiling without showing a menuconfig screen. 

Additionally i think it would be useful to check if the config folder in the ukam folder does exist and if not create it. I saw an error when that folder wasn't there already and the script didn't work.

**Comment by fbeauKmi** [comment]
Good Catch, thank you for the feedback.

Already prepared a fix https://github.com/fbeauKmi/update_klipper_and_mcus/pull/7

For the second point I need more investigation. The script already check and create ``./config/`` before trying to update mcu. It could be a side effect.

BTW, I'm happy you appreciate Ukam :)

**Comment by fbeauKmi** [comment]
I think the second point is solved too by #8 . My guess is the script attempts to create a link to ukam/config even if this folder doesn't exist.

Thanks for the feedback.
I'll close this issue, feel free to reopen it if you think I didn't solve the issue.

**Comment by thomasfjen** [comment]
> I think the second point is solved too by #8 . My guess is the script attempts to create a link to ukam/config even if this folder doesn't exist.
> 
> Thanks for the feedback. I'll close this issue, feel free to reopen it if you think I didn't solve the issue.

![Screenshot 2024-11-01 130140](https://github.com/user-attachments/assets/26101ce8-d3d2-4e22-9dff-c0779f669722)

Thank you for the quick fixes! :)
I can confirm that the make menuconfig does now show up as intentioned. 
The second issue i mentioned still appears. In the screenshot you can see the error i encouter when i try run the script without the config folder already created. The first error in the screenshot is because of a spelling error on my side :D

**Comment by fbeauKmi** [comment]
Ho ! I missed that. Thanks, the screenshot is really helpful. https://github.com/fbeauKmi/update_klipper_and_mcus/pull/9
